
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'release'
    repositoryName: 'UWAA/marketoMaster'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v*.*.*'
    isDraft: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
